# Generated by Django 3.0.7 on 2020-06-10 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdata',
            old_name='slug',
            new_name='link',
        ),
    ]
