# Generated by Django 3.0.7 on 2020-06-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20200610_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdata',
            name='cover_images',
            field=models.ImageField(default='', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
