# Generated by Django 3.0.7 on 2020-06-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_postdata_cover_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdata',
            old_name='cover_images',
            new_name='cover_image',
        ),
    ]
