# Generated by Django 3.0.7 on 2020-06-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20200610_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdata',
            name='Content',
        ),
        migrations.AlterField(
            model_name='postdata',
            name='cover_image',
            field=models.ImageField(default='', upload_to='documents/'),
        ),
    ]
