# Generated by Django 3.0.7 on 2020-06-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_postdata_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdata',
            name='contents',
        ),
        migrations.AddField(
            model_name='postdata',
            name='Content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
