# Generated by Django 3.0.7 on 2020-06-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0010_auto_20200611_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100), verbose_name='PostData Slug'),
        ),
    ]
