# Generated by Django 3.0.7 on 2020-06-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0017_auto_20200611_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
