# Generated by Django 3.0.7 on 2020-06-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0018_auto_20200612_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
